services:
  scambet:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
      - postgresql

  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - 27017:27017

  postgresql:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
    - ALLOW_EMPTY_PASSWORD=yes

volumes:
  mongodb_data:
  postgres_data:



