services:
  scambet:
    image: alexeidochub/scambet:v2
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
      - postgresql

  mongodb:
    image: mongodb/mongodb-community-server
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  postgresql:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=scambet
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  mongodb_data:
  postgres_data:



