name: Cleanup GitHub Registry Repo

permissions:

  contents: read

run-name: "Cleanup GitHub Registry Repo by @${{ github.actor }}"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

jobs:
  cleanup-container-registry:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Cleanup prd.scambet
        uses: dataaxiom/ghcr-cleanup-action@v1.0.16
        with:
          token: ${{ secrets.CR_PAT_CLEANUP }}
          package: prd.scambet
          delete-tags: "scambet*"
          keep-n-untagged: 0
          keep-n-tagged: 2

      - name: Cleanup stg.scambet
        uses: dataaxiom/ghcr-cleanup-action@v1.0.16
        with:
          token: ${{ secrets.CR_PAT_CLEANUP }}
          package: stg.scambet
          delete-tags: "scambet*"
          keep-n-untagged: 0
          keep-n-tagged: 2

      - name: Cleanup scambet
        uses: dataaxiom/ghcr-cleanup-action@v1.0.16
        with:
          token: ${{ secrets.CR_PAT_CLEANUP }}
          package: scambet
          delete-tags: "scambet*"
          keep-n-untagged: 0
          keep-n-tagged: 2
