name: Cleanup GitHub Registry Repo

permissions:

  contents: read

run-name: "Cleanup GitHub Registry Repo by @${{ github.actor }}"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

jobs:
  cleanup-container-registry:
    runs-on: ubuntu-latest
    permissions:
        packages: write
    steps:

      - name: GHCR.io Cleanup Action
        uses: dataaxiom/ghcr-cleanup-action@v1.0.16
        with:
          dry-run: true
          token: ${{ secrets.CR_PAT }}
          delete-tags: "*scambet"
          keep-n-untagged: 3
