name: Cleanup GitHub Registry Repo

permissions:
  packages: write

run-name: "Action: from branch ${{ github.ref_name }} by @${{ github.actor }}"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

jobs:
  cleanup-container-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: GHCR.io Cleanup Action
        uses: dataaxiom/ghcr-cleanup-action@v1.0.16
        with:
          dry-run: true
