  name: Start/Stop Scambet

  permissions:
    id-token: write  
    contents: read

  run-name: Build Backend and Deploy from branch ${{ github.ref_name }} by @${{ github.actor }}

  on:
    workflow_dispatch:

  jobs:
    Start-or-Stop:
      runs-on: ubuntu-latest
      
      steps:
      
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-region: eu-central-1
            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-for-EC2-full
            role-session-name: FrontendDeployment
            audience: sts.amazonaws.com
            
        - name: Check instances
          run: aws ec2 describe-instances --region eu-central-1 --output json
          
