name: Scambet - Check or Stop

permissions:
  id-token: write  
  contents: read

run-name: " Action: ${{ github.event.inputs.action }} from branch ${{ github.ref_name }} by @${{ github.actor }}" 

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose an action Stop or Check"
        type: choice
        required: true
        options: 
          - Stop
          - Check


jobs:
  Check-or-Stop:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-for-EC2-full
          role-session-name: FrontendDeployment
          audience: sts.amazonaws.com
          
      - name: Check Scambet Instances
        if: github.event.inputs.action == 'Check'
        run: |

          INSTANCE_JSON=$(aws ec2 describe-instances --region eu-central-1 --output json)


          STOPPED_INSTANCE_IDS=$(echo "$INSTANCE_JSON" | jq -r '
            .Reservations[].Instances[]
            | select(.State.Name == "stopped")
            | .InstanceId')

          if [ -z "$STOPPED_INSTANCE_IDS" ]; then
            echo "✅ Scambet is up (no stopped instances)."
          else
            echo "🖥️ Found stopped instance(s): $STOPPED_INSTANCE_IDS"


            STOPPED_INSTANCE_NAMES=$(echo "$INSTANCE_JSON" | jq -r '
              .Reservations[].Instances[]
              | select(.State.Name == "stopped")
              | [.Tags[]? | select(.Key == "Name") | .Value] | join(", ")')

            echo "🔍 Names of stopped instances: $STOPPED_INSTANCE_NAMES"
          fi


      - name: Stop Scambet Instances
        if: github.event.inputs.action == 'Stop'
        run: |
        
          INSTANCE_JSON=$(aws ec2 describe-instances --region eu-central-1 --output json)

          INSTANCE_IDS=$(echo "$INSTANCE_JSON" | jq -r '
            .Reservations[].Instances[]
            | select(.State.Name == "running" or .State.Name == "pending")
            | .InstanceId')

          INSTANCE_NAMES=$(echo "$INSTANCE_JSON" | jq -r '
            .Reservations[].Instances[]
            | select(.State.Name == "running" or .State.Name == "pending")
            | [.Tags[]? | select(.Key == "Name") | .Value] | join(", ")')


          if [ -z "$INSTANCE_IDS" ]; then
            echo "✅ Scambet is already stopped. No running or pending instances."
          else
            echo "🛑 Stopping Instances with ID(s): $INSTANCE_IDS"
            echo "🖥️ Name(s): $INSTANCE_NAMES"

            aws ec2 stop-instances --region eu-central-1 --instance-ids $INSTANCE_IDS
            aws ec2 wait instance-stopped --region eu-central-1 --instance-ids $INSTANCE_IDS
            echo "✅ Instances fully stopped."
          fi

